
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import PageHeader from '@/components/shared/PageHeader';
import DataTable, { Column } from '@/components/shared/DataTable';
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

// Sample data
const initialHistory = [
  {
    id: '1',
    date: '2023-08-01',
    generatedBy: 'John Doe',
    start: '08:00',
    end: '17:00',
    totalPMSchedule: 25,
    totalWOGenerated: 18,
    totalProblem: 3,
  },
  {
    id: '2',
    date: '2023-08-15',
    generatedBy: 'Jane Smith',
    start: '09:00',
    end: '16:30',
    totalPMSchedule: 30,
    totalWOGenerated: 28,
    totalProblem: 0,
  },
  {
    id: '3',
    date: '2023-09-01',
    generatedBy: 'Michael Johnson',
    start: '07:30',
    end: '18:00',
    totalPMSchedule: 40,
    totalWOGenerated: 35,
    totalProblem: 5,
  },
  {
    id: '4',
    date: '2023-09-15',
    generatedBy: 'Sarah Williams',
    start: '08:30',
    end: '17:30',
    totalPMSchedule: 22,
    totalWOGenerated: 20,
    totalProblem: 2,
  },
  {
    id: '5',
    date: '2023-10-01',
    generatedBy: 'David Brown',
    start: '09:00',
    end: '16:00',
    totalPMSchedule: 18,
    totalWOGenerated: 15,
    totalProblem: 1,
  },
  {
    id: '6',
    date: '2023-10-15',
    generatedBy: 'Emily Davis',
    start: '08:00',
    end: '18:00',
    totalPMSchedule: 35,
    totalWOGenerated: 32,
    totalProblem: 4,
  },
  {
    id: '7',
    date: '2023-11-01',
    generatedBy: 'Kevin Wilson',
    start: '07:00',
    end: '16:00',
    totalPMSchedule: 28,
    totalWOGenerated: 25,
    totalProblem: 2,
  },
];

const WOHistoryPage: React.FC = () => {
  const navigate = useNavigate();
  const [history, setHistory] = useState(initialHistory);

  const columns: Column[] = [
    { id: 'date', header: 'Date', accessorKey: 'date' },
    { id: 'generatedBy', header: 'Generated By', accessorKey: 'generatedBy' },
    { id: 'start', header: 'Start', accessorKey: 'start' },
    { id: 'end', header: 'End', accessorKey: 'end' },
    { id: 'totalPMSchedule', header: 'Total PM Schedule', accessorKey: 'totalPMSchedule' },
    { id: 'totalWOGenerated', header: 'Total WO Generated', accessorKey: 'totalWOGenerated' },
    { id: 'totalProblem', header: 'Total Problem', accessorKey: 'totalProblem' },
  ];

  // Calculate summary statistics
  const totalPMSchedules = history.reduce((sum, item) => sum + item.totalPMSchedule, 0);
  const totalWOGenerated = history.reduce((sum, item) => sum + item.totalWOGenerated, 0);
  const totalProblems = history.reduce((sum, item) => sum + item.totalProblem, 0);
  
  const handleRowClick = (row: any) => {
    navigate(`/maintain/wo-history/${row.id}`);
  };

  return (
    <div className="space-y-6">
      <PageHeader 
        title="WO History" 
        onSearch={(query) => console.log('Search:', query)}
      />
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total PM Schedules
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalPMSchedules}</div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Work Orders Generated
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalWOGenerated}</div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Problems
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalProblems}</div>
          </CardContent>
        </Card>
      </div>
      
      <DataTable 
        columns={columns}
        data={history}
        onRowClick={handleRowClick}
      />
    </div>
  );
};

export default WOHistoryPage;
